export type DocStep = { title: string; body: string; command?: string; windows?: string; expected?: string; href?: string; link?: string };
export type DocGuide = { slug: string; number: string; title: string; summary: string; status: string; runsOn: string; needs: string; boundary: string; steps: DocStep[]; table?: { headings: string[]; rows: string[][] }; related?: string[]; troubleshooting?: { problem: string; resolution: string }[]; sources?: { title: string; url: string }[] };
export type DocGroup = { title: string; slugs: string[] };
export const docGroups: DocGroup[] = [
  { title: "Using 10Signals", slugs: ["using-10signals"] },
  { title: "10Signals Cloud", slugs: ["hosted"] },
  { title: "Self-hosting", slugs: ["self-host", "ai-provider"] },
  { title: "CLI & Trigger", slugs: ["trigger-cli", "trigger-credentials", "own-trigger"] },
  { title: "API & MCP", slugs: ["api", "mcp"] },
  { title: "Reference", slugs: ["credentials", "troubleshooting"] },
];

export const docGuides: DocGuide[] = [
  { slug: "hosted", number: "01", title: "10Signals Cloud", summary: "Use the managed service, your account and hosted allowances.", status: "Hosted service", runsOn: "Our managed infrastructure", needs: "A 10Signals account and report allowance", boundary: "Nothing to install. Your account owns your reports; a report becomes public only when you explicitly share it. These links open the hosted service, not your local installation.", related: ["using-10signals", "api", "mcp"], steps: [
    { title: "Create your account", body: "Sign in or create an account. Your reports and connection settings live in Account.", href: "https://10signals.xyz/account", link: "Open your hosted account", expected: "Your account page shows your available allowance and reports." },
    { title: "Create a report", body: "Enter your own store domain. Choose a comparison target and optionally close-price matching. A comparison is one priced primary/rival product pair—not one scraped product.", href: "https://10signals.xyz/", link: "Start a hosted report", expected: "The progress screen opens, then the report shows delivered comparisons and any shortfall." },
    { title: "Read the evidence", body: "Open the original and rival product links. Prices are observed public offers. Search matches are inferred alternatives, not guaranteed identical products or savings." },
    { title: "Watch prices only when you choose", body: "Use an item's switch for that product, or the competitor-level control for a rival's products. Review cadence and credit cost before enabling. One product check uses one credit.", href: "https://10signals.xyz/price-watch", link: "Open hosted price watches" },
  ] },
  { slug: "trigger-cli", number: "02", title: "Connect the Trigger CLI", summary: "Install a client for a Trigger environment that already has the tools.", status: "Public preview", runsOn: "The Trigger environment selected by your key", needs: "Node.js 22+ and an authorized Trigger environment key", boundary: "This installs the client only. It does not install 10Signals or deploy task code. Company Trigger access is for trusted colleagues—not external customers.", steps: [
    { title: "Check Node.js", body: "Install Node.js 22 or later first if this command is unavailable. Open a new terminal after installation.", command: "node --version", href: "https://nodejs.org/en/download", link: "Get Node.js", expected: "A version of v22 or later." },
    { title: "Install the package", body: "Run from any folder. No GitHub or npm login is needed. The preview includes the native executable; a repository checkout is not required.", command: "npm install --global @10signals/cli@preview", windows: "npm.cmd install --global @10signals/cli@preview", expected: "npm reports that the package was added." },
    { title: "Verify the installed client", body: "This prints the client revision. It is different from the Trigger worker version.", command: "marketsignal-trigger version", windows: "marketsignal-trigger.cmd version", expected: "A build revision, not ‘command not found’." },
    { title: "Connect your environment", body: "Get the secret for the intended project and environment from Trigger → API keys, or your authorized operator. Paste it only at the hidden prompt. The client verifies it and saves it in your OS credential store. TRIGGER_SECRET_KEY in your terminal overrides that saved key. Never put a key in chat, screenshots or command arguments.", command: "marketsignal-trigger configure", windows: "marketsignal-trigger.cmd configure", expected: "The key is verified and saved. No report is started.", href: "/docs/trigger-credentials", link: "Runtime keys versus deployment login" },
    { title: "Check the deployed tools", body: "This check makes no AI/search-provider calls. It must finish successfully. If providerConfigured is false, ask your operator to configure the research provider in Trigger before creating a report. If it stays PENDING_VERSION, your operator must promote a worker containing the Direct CLI tasks. Waiting longer is not a repair.", command: "marketsignal-trigger doctor", windows: "marketsignal-trigger.cmd doctor", expected: "COMPLETED, status ready, and four Direct CLI tasks. Research additionally requires providerConfigured true." },
    { title: "Create your first report", body: "Answer the domain, comparison count, and search-mode questions. The final confirmation starts paid research. Request IDs are automatic, and results appear in this command without a second wait command.", command: "marketsignal-trigger report", windows: "marketsignal-trigger.cmd report", expected: "A run ID, progress messages, then structured JSON with comparisons, competitors, metrics and limitations." },
    { title: "Use it from another agent", body: "Replace the domain placeholder. Argument mode submits immediately without the interactive confirmation. Add --close-price for the default ±30% same-currency displayed-price range. Never auto-retry a submission when its outcome is uncertain.", command: 'marketsignal-trigger report "<your-domain>" --comparisons 20 --close-price', windows: 'marketsignal-trigger.cmd report "<your-domain>" --comparisons 20 --close-price' },
    { title: "Read an existing result", body: "Use the run ID printed by your report command. Retrieving does not launch new research. The Windows command displays JSON directly; the macOS/Linux command saves it. Avoid Windows PowerShell 5.1 redirection for JSON files because it changes their encoding.", command: 'marketsignal-trigger result "<run-id>" > report.json', windows: 'marketsignal-trigger.cmd result "<run-id>"' },
  ] },
  { slug: "self-host", number: "03", title: "Self-host 10Signals", summary: "Install the full project and research worker on your own computer.", status: "Local quickstart preview", runsOn: "Your own computer; localhost only", needs: "Git, Docker with Compose 2.24+, your own provider key for research", boundary: "This is the full project, not the Trigger CLI. The four-command prebuilt-image preview is for owner testing; do not use these commands on the old source-build branch. No Node.js, GitHub login or certificate installation is needed. Existing HTTPS installations remain separate.", steps: [
    { title: "Choose where research runs", body: "Local execution means the application and worker run on your infrastructure. AI/search requests still need your own provider account and may cost money. The alternative is your own Trigger project; it must not use our company key." },
    { title: "Clone 10Signals", body: "The default public main branch includes the local quickstart and AI provider settings; no feature branch is needed. Choose a new folder name if 10signals already exists. This is a local preview, not a hardened public-server release.", command: "git clone https://github.com/BlyzrHQ/10signals-self-host.git 10signals", expected: "A new 10signals folder containing the project and local-only compose.yaml." },
    { title: "Open the project folder", body: "Run all following commands from this folder.", command: "cd 10signals" },
    { title: "Configure 10Signals", body: "Docker pulls the prebuilt image and creates private .env configuration automatically. No key is requested in the terminal. Existing configuration is never overwritten.", command: "docker compose run --rm setup", expected: "Private configuration saved, with the address http://localhost:8787." },
    { title: "Start 10Signals", body: "Starts the app, storage and worker together. Open http://localhost:8787 only after all three services are healthy, then create a local account. If the port is allocated, an older installation may open instead: stop it from its own folder or choose a free port with setup --port before first configuration. Keep the loopback-only binding; do not expose this HTTP preview to the network.", command: "docker compose up -d --wait", expected: "Web, worker and gateway are healthy. Without a provider key, the app explains that research is disabled." },
    { title: "Connect your AI provider", body: "Open Account → AI provider. You should see a masked OpenAI API key field and Test & save. Enter your own key there, not in a terminal command. Authentication and required model access are checked without generating a report. Billing credit and inference are checked when you run a report. Keys are encrypted per account; replacing or removing one needs no worker restart.", href: "/account?section=provider", link: "Open this installation's AI provider settings", expected: "Key and model access checked. Saved for your account. You can now create a report." },
    { title: "Acceptance checklist", body: "Start with empty storage; create an account; add your provider key; run a real-domain report; test private/share access; restart and verify persistence. Scheduled watches are not enabled in this local preview. A home page loading successfully is not full installation acceptance." },
  ] },
  { slug: "own-trigger", number: "04", title: "Set up your own Trigger project", summary: "Understand the operator setup and what is not released yet.", status: "Installer not released", runsOn: "Your own Trigger Cloud project", needs: "An isolated deployment package, operator access and your own provider account", boundary: "The public local quickstart does not include a released own-Trigger installer. Do not run a missing setup script or repurpose the company's deployment configuration. A runtime environment key runs installed tasks; it does not install them. Empty-project deployment remains unverified.", related: ["trigger-credentials", "trigger-cli", "self-host"], steps: [
    { title: "Choose installation or connection", body: "If your environment already contains the four Direct tools, use the CLI guide now. If it is empty, pause here: installing the npm client will not add tools to Trigger.", href: "/docs/trigger-cli", link: "Connect to installed tools" },
    { title: "Prepare the operator details", body: "Identify the organization, a dedicated new project, its non-secret project reference, and the target environment. Use staging for acceptance. Do not copy company project identifiers, callback secrets or databases." },
    { title: "Separate deployment access from runtime access", body: "Interactive operators use Trigger login with a separate named profile. Trigger also supports TRIGGER_ACCESS_TOKEN for CI deployment, but our isolated setup candidate currently uses interactive login and does not support unattended PAT provisioning. No deployment command is offered until the isolated package is released.", href: "/docs/trigger-credentials", link: "Choose the right authentication method" },
    { title: "Configure the worker's provider", body: "The operator must set their own OPENAI_API_KEY in the target Trigger environment. A local Account → AI provider key does not configure Trigger. Do not share provider keys or deployment PATs with report agents." },
    { title: "Acceptance before promotion", body: "The release gate is: isolated upload, verify installed tasks, configure runtime CLI, run doctor against the candidate version, complete one approved real report, then inspect pending runs and explicitly approve promotion. Deployment success alone is not proof that unpinned commands use the new worker." },
    { title: "Use the available alternative", body: "For a complete installation today, test the local Docker quickstart. It runs its own worker and does not need a Trigger account.", href: "/docs/self-host", link: "Install the local preview" },
  ] },
  { slug: "api", number: "05", title: "Connect through the API", summary: "Let an external client use its own 10Signals account.", status: "Onboarding fixes: test candidate", runsOn: "Our hosted service", needs: "An account-scoped 10Signals API key", boundary: "This is external service access, not internal Trigger access. Customers need no Trigger, provider, VPS or company credentials. Hosted allowances still apply. The new list/status fixes await owner testing and are not yet deployed; self-hosted API support is not released.", steps: [
    { title: "Create a scoped key", body: "Open the hosted Account → API keys. Start read-only, set an expiry, and copy it once into your secret manager. Use separate keys for separate clients.", href: "https://10signals.xyz/account?section=keys", link: "Open hosted API keys" },
    { title: "Enter the key privately", body: "Run in your terminal. The prompt hides the key; do not paste it into source code or a command argument. Keep this terminal open for the next step.", windows: '$secret = Read-Host "Account API key" -AsSecureString\n$credential = [pscredential]::new("api", $secret)\n$headers = @{Authorization = "Bearer " + $credential.GetNetworkCredential().Password}', command: "printf 'Account API key: '; IFS= read -r -s SIGNALS_API_KEY; printf '\\n'" },
    { title: "Check access without spending a report", body: "This returns only your account's reports. An empty page is valid for a new account. No research starts. A revoked key returns 401.", windows: 'Invoke-RestMethod "https://10signals.xyz/api/reports?limit=10" -Headers $headers', command: 'curl --fail-with-body -H "Authorization: Bearer $SIGNALS_API_KEY" "https://10signals.xyz/api/reports?limit=10"', expected: 'ok: true, contractVersion: "1", page.items, and page.nextCursor.' },
    { title: "Prepare a paid request", body: "Switch to a create-and-read key. Replace the domain placeholder below. Hosted subscriptions use the comparison count of your plan; do not assume a smaller requested count changes that entitlement. Generate this request ID once, retaining it for an uncertain retry of the same request. The interactive Trigger CLI handles IDs for you; this low-level HTTP walkthrough makes idempotency explicit.", windows: '$requestId = [guid]::NewGuid().ToString()\n$body = @{primaryDomain="<your-domain>"; closePricePercent=30; commandId=$requestId} | ConvertTo-Json', command: 'REQUEST_ID=$(uuidgen)\nDOMAIN="<your-domain>"' },
    { title: "Submit once", body: "This starts paid work immediately. Omit closePricePercent for broad matching. Save the returned report.publicId and requestId. HTTP 202 means accepted, not finished. Do not regenerate the request ID after a timeout; inspect the existing request first.", windows: '$created = Invoke-RestMethod "https://10signals.xyz/api/reports" -Method Post -Headers $headers -ContentType "application/json" -Body $body\n$created', command: 'curl --fail-with-body -H "Authorization: Bearer $SIGNALS_API_KEY" -H "Content-Type: application/json" -d "{\\"primaryDomain\\":\\"$DOMAIN\\",\\"closePricePercent\\":30,\\"commandId\\":\\"$REQUEST_ID\\"}" https://10signals.xyz/api/reports', expected: "HTTP 202 with report.publicId and requestId; a 402 means hosted allowance is required." },
    { title: "Read status and structured results", body: "Use the returned report ID. Poll no faster than every ten seconds and respect Retry-After. A terminal result can be complete, partial or failed. The result/comparisons endpoint with the same requestId provides further comparison pages. A missing, expired or unauthorized report returns 404 without revealing whether it belongs to someone else.", windows: '$reportId = $created.report.publicId\nInvoke-RestMethod "https://10signals.xyz/api/reports/$reportId" -Headers $headers\nInvoke-RestMethod "https://10signals.xyz/api/reports/$reportId/result?requestId=$requestId" -Headers $headers | ConvertTo-Json -Depth 100', command: 'REPORT_ID="<returned-report-id>"\ncurl --fail-with-body -H "Authorization: Bearer $SIGNALS_API_KEY" "https://10signals.xyz/api/reports/$REPORT_ID"\ncurl --fail-with-body -H "Authorization: Bearer $SIGNALS_API_KEY" "https://10signals.xyz/api/reports/$REPORT_ID/result?requestId=$REQUEST_ID"', expected: "Owned report state, then structured comparisons, competitors, source links and limitations." },
    { title: "Revoke and verify", body: "Revoke the test key in Account. Repeat the list check and confirm 401. Close the terminal to discard in-memory secret variables. Read-only denial, account isolation and revocation have automated tests; a live paid new-customer lifecycle remains an acceptance gate." },
    { title: "Which CLI is this?", body: "The customer binary is marketsignal and uses an account key. The public @10signals/cli preview installs marketsignal-trigger for internal/own-Trigger use, not the customer binary. The HTTP commands above need no extra client package." },
  ] },
  { slug: "mcp", number: "06", title: "Connect an AI agent with MCP", summary: "Give an agent scoped report and price-watch tools.", status: "Discovery checked / client acceptance pending", runsOn: "Our hosted service", needs: "A compatible OAuth MCP client and your account consent", boundary: "An account API key is not an MCP OAuth token. No Trigger key is needed. Your agent must ask before paid report creation or recurring price checks. Live discovery was checked; external-client login is still an acceptance gate. Independent self-hosted OAuth is not released.", steps: [
    { title: "Add the remote MCP server", body: "In your client's remote-server settings, use the hosted endpoint below. This connects to our service; it does not install a local server.", command: "https://10signals.xyz/mcp" },
    { title: "Authorize your account", body: "Follow the client's OAuth sign-in and consent flow. Start with reports:read. Review the actual client host. Codex CLI 0.144.1 failed registration in our test; 0.154.0 generated the correct authorization request, but account consent and tool calls remain unverified. Open the printed link in your regular browser if it does not open automatically. Do not work around an OAuth error by sharing a company key." },
    { title: "Start read-only", body: "Ask your agent to call account_status and reports_list, then report_get and report_matches_list for an owned report. Empty history is valid for a new account. These checks must not create reports or watches.", command: "List my reports and show one report's comparison evidence. Do not create a report or enable any price watches." },
    { title: "Control paid work explicitly", body: "report_create_preview shows the current plan's comparison count and allowance impact; only report_create_confirm starts work. price_watch_preview shows product/rival scope, cadence and credits; only price_watch_confirm activates. Keep the same token for an uncertain retry. Disable the test watch with price_watch_disable. Tokens expire after five minutes; obtain a new preview if impact changes or the token expires." },
    { title: "Run the no-cost diagnostic", body: "From the source candidate, this Node.js command checks public metadata and the unauthenticated 401 challenge. It does not log in, access your data or call paid tools. A successful check is not proof of client compatibility.", command: "node scripts/check-mcp-connection.mjs", windows: "node scripts/check-mcp-connection.mjs", expected: "discovery: available; authentication: required; clientLoginTested: false; toolsTested: false." },
    { title: "Revoke the test connection", body: "Remove the OAuth connection from the hosted Account → Connected apps and verify access fails. API keys are separate and must be revoked separately.", href: "https://10signals.xyz/account?section=apps", link: "Open hosted connected apps" },
  ] },
  { slug: "using-10signals", number: "08", title: "Using 10Signals", summary: "Understand reports, comparisons and the evidence behind them.", status: "Product guide", runsOn: "Cloud or your own installation", needs: "Access to a running 10Signals account", boundary: "These concepts apply to both editions. Installation, provider keys and billing are explained in their own guides. Feature availability differs: scheduled price watches are not enabled in the local preview.", related: ["hosted", "self-host", "credentials"], steps: [
    { title: "Start with a domain", body: "Submit the public store domain you want to research. A requested comparison target counts priced original/rival pairs, not the total number of products crawled. Coverage depends on accessible evidence." },
    { title: "Choose broad or close-price matching", body: "Broad search finds relevant alternatives across prices. Close-price search keeps displayed offers within the selected percentage range in the same currency; the default is ±30%. There is no currency conversion. Similar prices do not prove identical quality or positioning." },
    { title: "Inspect the result", body: "Use Products for original/rival pairs and source links, and Competitors for the sellers represented. Follow the original links before making a commercial decision. A price is an observed offer at a point in time, not a guaranteed current checkout price." },
    { title: "Read coverage and quality states", body: "Missing prices, blocked pages and limited matches are gaps, not zero values. Distinguish public observations, inferred matches and optional AI recommendations. A completed job may still deliver fewer comparisons than requested." },
    { title: "Keep reports private or share deliberately", body: "Your account owns its saved reports. Share only through an explicit sharing control after reviewing the information. API and MCP access are separate, scoped connections; they do not make a report public." },
  ] },
  { slug: "ai-provider", number: "09", title: "Configure your AI provider", summary: "Add, test, replace or remove your own research key.", status: "Local preview", runsOn: "Your local account and research worker", needs: "The local quickstart and your own OpenAI API key", boundary: "This screen configures only the local installation. It does not change our company account, the hosted service or a Trigger project. Successful key validation is not proof of available billing credit or a completed research run.", related: ["self-host", "trigger-credentials"], steps: [
    { title: "Open your local account", body: "Create or sign in to an account in your running local installation. Choose Account → AI provider. Confirm the address is your localhost instance before entering a key.", href: "/account?section=provider", link: "Open provider settings on this installation" },
    { title: "Test and save your key", body: "Enter your own OpenAI API key in the password field and select Test & save. The server checks authentication and required model access, then stores the key encrypted for your account. The key is never included in an MCP configuration.", expected: "The provider is shown as configured. No report has been generated." },
    { title: "Run an approved test", body: "Submit your own public domain in the app. This is the point where research uses your provider account. Check delivered comparisons, evidence and limitations, not only the terminal job state." },
    { title: "Replace or remove access", body: "Use the same screen to replace or remove the saved key; no worker restart is needed. New and queued work uses the updated configuration. Already running work may retain the key it loaded at start. Removal here does not revoke the key at the provider." },
  ], troubleshooting: [
    { problem: "Validation succeeds, but research fails", resolution: "Validation checks authentication and model visibility. A report also needs provider billing capacity and successful inference. Inspect the report's sanitized failure state; do not keep resubmitting blindly." },
    { problem: "The worker is not ready", resolution: "Run docker compose ps from the installation folder. Web, worker and gateway should be healthy. Check the local troubleshooting guide before starting another report." },
  ] },
  { slug: "trigger-credentials", number: "10", title: "Trigger keys and operator login", summary: "Choose the credential for running tools, deploying code or powering research.", status: "Verified reference · 13 Sep 2026", runsOn: "Trigger Cloud; separate from local 10Signals", needs: "Authorized access to the intended project and environment", boundary: "There is no single key that installs everything. The current marketsignal-trigger client accepts environment secret keys, not deployment PATs, 10Signals account keys. It connects to api.trigger.dev; a custom/self-hosted Trigger endpoint is not supported by this client.", related: ["trigger-cli", "own-trigger", "credentials"], table: { headings: ["Purpose", "Credential", "Where it belongs"], rows: [
    ["Run already installed tasks", "Trigger environment secret key", "CLI configure or TRIGGER_SECRET_KEY in the agent's process"],
    ["Deploy task code interactively", "Trigger operator login", "A separate named Trigger CLI profile"],
    ["Deploy from CI", "Operator personal access token (PAT)", "TRIGGER_ACCESS_TOKEN in a protected CI secret; not report-agent config"],
    ["Power research", "Your OpenAI API key", "OPENAI_API_KEY in the selected Trigger worker environment"],
  ] }, steps: [
    { title: "Runtime: select the right environment", body: "In your Trigger project, open API keys and select the intended environment. Get its secret through that dashboard or your authorized operator. Treat it as broad trusted environment access, not a narrowly scoped 10Signals customer key. Install the client before continuing.", href: "/docs/trigger-cli", link: "Install and connect the CLI" },
    { title: "Runtime: verify and store", body: "The hidden prompt verifies and stores the key in the OS credential store. No task code is installed and no research is started. A verified key does not prove that the four Direct tools or provider are configured.", command: "marketsignal-trigger configure", windows: "marketsignal-trigger.cmd configure", expected: "Trigger key verified and saved. Next, run doctor." },
    { title: "Headless agents: use secret injection", body: "Inject TRIGGER_SECRET_KEY from your secret manager into the report-agent process, or use the secure stdin configure option when an OS credential store is available. Do not place secrets in command arguments. TRIGGER_SECRET_KEY takes priority over the saved key. Our CLI currently has one saved runtime credential, not named runtime profiles; use isolated processes for different environments." },
    { title: "Operator: use a separate login profile", body: "For deployment operators only. This opens Trigger authentication and creates a named login profile; it does not install 10Signals tasks. The pinned version matches this source's Trigger SDK. This profile is separate from the runtime credential saved by marketsignal-trigger configure.", command: "npx trigger.dev@4.5.4 login --profile 10signals-own", windows: "npx.cmd trigger.dev@4.5.4 login --profile 10signals-own", expected: "Trigger authentication completes for your operator account and named profile." },
    { title: "CI: keep PATs out of client setup", body: "Trigger's CI deployment method uses TRIGGER_ACCESS_TOKEN. Create a PAT in the operator profile's Personal Access Tokens settings and store it in a protected CI environment only. A PAT inherits broader user access; it is not interchangeable with the runtime secret key. Our own-project installer candidate does not yet accept unattended PAT setup. Do not paste a PAT into configure.", href: "https://trigger.dev/docs/github-actions", link: "Trigger's official CI authentication guide" },
    { title: "Worker: configure research separately", body: "In the selected Trigger environment's variables, set your own OPENAI_API_KEY. Do not copy a local .env or company secrets into another project. After the tools are deployed, doctor should complete with providerConfigured true. That boolean is configuration presence, not a live inference or billing test." },
    { title: "Remove or rotate access", body: "logout removes this client's saved key only. It does not revoke the key in Trigger and does not unset a process's TRIGGER_SECRET_KEY. Revoke or rotate keys at their issuing service, update authorized secret stores, and close old agent processes.", command: "marketsignal-trigger logout", windows: "marketsignal-trigger.cmd logout" },
  ], troubleshooting: [
    { problem: "configure succeeded, but commands use another project", resolution: "Check whether TRIGGER_SECRET_KEY is set without displaying its value. It overrides the OS-stored key. Start a clean terminal or remove the unintended variable, then run doctor." },
    { problem: "doctor remains PENDING_VERSION", resolution: "An operator must inspect the task and worker version. Use the same explicitly supplied candidate pin for doctor and report, or promote only after approval. Waiting or reinstalling the client does not deploy a worker." },
    { problem: "A runtime key cannot deploy the project", resolution: "Use operator authentication for deployment. The public isolated own-project installer is not released; do not substitute the company deployment config." },
  ], sources: [
    { title: "Trigger: environment API keys", url: "https://trigger.dev/docs/apikeys" },
    { title: "Trigger: login profiles", url: "https://trigger.dev/docs/cli-login-commands" },
    { title: "Trigger: management authentication and PAT scope", url: "https://trigger.dev/docs/management/authentication" },
    { title: "Trigger: CI deployment", url: "https://trigger.dev/docs/github-actions" },
  ] },
  { slug: "credentials", number: "11", title: "Which key do I need?", summary: "One reference for account, agent, provider and deployment credentials.", status: "Connection reference", runsOn: "The service or installation you explicitly select", needs: "A credential issued for that exact destination", boundary: "These credentials are not interchangeable. External customers should never receive company Trigger, provider, deployment or VPS credentials.", related: ["trigger-credentials", "api", "mcp"], table: { headings: ["Connection", "Use", "Does not do"], rows: [
    ["Hosted API", "Account → API keys on 10signals.xyz; Bearer header", "Install code or access a Trigger project"],
    ["Hosted MCP", "Client OAuth consent to your hosted account", "Accept an account API key as an OAuth token"],
    ["Trigger runtime CLI", "Trigger environment secret; configure or TRIGGER_SECRET_KEY", "Deploy tools or install the app"],
    ["Trigger deployment", "Operator login, or PAT in protected CI", "Replace the runtime key for our report client"],
    ["Research provider", "Local AI provider screen OR Trigger OPENAI_API_KEY", "Authenticate an agent to 10Signals"],
  ] }, steps: [
    { title: "Identify the destination first", body: "Choose your local installation, the managed 10Signals service, or a trusted Trigger environment. A successful sign-in to one does not configure the others." },
    { title: "Start with the minimum access", body: "Use read-only account or MCP scopes for a first connection test. Trigger environment keys have a wider trust boundary: give them only to authorized teammates and agents." },
    { title: "Keep lifecycle actions separate", body: "Client logout, connection revocation and provider-key rotation have different effects. Revoke at the issuing service, remove stale environment variables and verify that new requests fail. Do not assume previously returned data is erased." },
  ] },
  { slug: "troubleshooting", number: "12", title: "Troubleshooting", summary: "Find the failing layer before repeating a request.", status: "Diagnostic guide", runsOn: "Your selected installation or connection", needs: "The command, client revision, run ID and sanitized error", boundary: "Never share API keys, tokens, cookies, private .env files or complete environment dumps. A queued run or successful key check is not a completed report.", related: ["trigger-cli", "trigger-credentials", "self-host", "mcp"], steps: [
    { title: "Check the client and destination", body: "For the Trigger CLI, run version and inspect which executable your shell selected. Old copies can shadow the npm command. For MCP, use https://10signals.xyz/mcp and sign in to your hosted account." },
    { title: "Check readiness before research", body: "For Trigger, doctor must complete on the intended worker. For local Docker, use the command below in the installation folder; all three services should be healthy. Neither check proves a paid provider request will succeed.", command: "docker compose ps", expected: "Local installation only: web, worker and gateway show healthy." },
    { title: "Inspect the existing run", body: "Use the saved report or Trigger run ID when submission is uncertain. Read-only retrieval does not start research. Do not generate a new submission just because the first command timed out." },
  ], troubleshooting: [
    { problem: "command not found", resolution: "Install @10signals/cli@preview first. Reopen your terminal, check PATH, and use marketsignal-trigger.cmd in Windows PowerShell if the script shim is blocked." },
    { problem: "Request ID required", resolution: "You are likely invoking an older client. Reinstall the preview and check its revision/path. Current interactive report commands generate the request ID; do not try to fix the client by changing a worker pin." },
    { problem: "MCP 401", resolution: "Sign in again through the MCP client. Check whether access expired or was revoked in hosted Account → Connected apps. An API key cannot replace OAuth consent." },
    { problem: "MCP 403", resolution: "Check the scopes granted to your agent and the hosted endpoint. Read-only connections cannot create reports or enable watches. Do not disable authorization checks." },
    { problem: "research-setup-required", resolution: "Save your own key in local AI provider settings and check worker health. The failed preflight did not create a report." },
    { problem: "Fewer comparisons than requested", resolution: "Inspect missing-price and access-failure evidence. A target is not guaranteed coverage. Keep original links and limitations attached when sharing the result." },
  ] },
].sort((left, right) => left.number.localeCompare(right.number));

export function searchDocGuides(guides: DocGuide[], query: string) {
  const terms = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  return guides.filter(guide => {
    const text = [guide.title, guide.summary, guide.needs, guide.boundary,
      ...guide.steps.flatMap(step => [step.title, step.body, step.command || "", step.windows || ""])].join(" ").toLocaleLowerCase();
    return terms.every(term => text.includes(term));
  });
}
