export type DocStep = { title: string; body: string; command?: string; windows?: string; expected?: string; href?: string; link?: string };
export type DocGuide = { slug: string; number: string; title: string; summary: string; status: string; runsOn: string; needs: string; boundary: string; steps: DocStep[] };

export const docGuides: DocGuide[] = [
  { slug: "local-mcp", number: "07", title: "Local MCP connections", summary: "Connect Claude Code or Codex to your self-hosted account.", status: "Local preview", runsOn: "Your own computer and local worker", needs: "A running local installation and a local MCP client", boundary: "This is separate from hosted MCP and company Trigger access. The agent uses a scoped connection token, never your OpenAI key. Cloud connectors cannot access localhost.", steps: [
    { title: "Create a read-only connection", body: "Open Account → MCP connections. Name the connection, choose Read reports only and an expiry, then Create connection. Copy its token now; it is shown once.", href: "/account?section=local-mcp", link: "Manage local MCP connections" },
    { title: "Load your token privately", body: "Paste the connection token at the hidden prompt. Keep this terminal open and start your agent from it. Never print the variable or place the token in Git or chat.", windows: "$env:TEN_SIGNALS_MCP_TOKEN = [System.Net.NetworkCredential]::new('', (Read-Host 'Local MCP connection token' -AsSecureString)).Password", command: "printf 'Local MCP connection token: '\nIFS= read -r -s TEN_SIGNALS_MCP_TOKEN\nprintf '\\n'\nexport TEN_SIGNALS_MCP_TOKEN" },
    { title: "Choose Claude Code or Codex", body: "For Claude Code, download Claude configuration from Account → MCP connections, save it as 10signals.mcp.json in a test folder, then run the command below from that folder. The file uses your token environment variable. For Codex, use the next alternative step instead.", command: "claude --mcp-config ./10signals.mcp.json", windows: "claude.cmd --mcp-config ./10signals.mcp.json", expected: "Approve the local server, then /mcp shows a connected server." },
    { title: "Alternative: Codex CLI", body: "If you chose Codex instead, register the endpoint once, replacing 8787 with the port shown in Account. Then run codex in this same terminal. Do not run OAuth login for this local server.", command: "codex mcp add tensignals-local --url http://localhost:8787/mcp --bearer-token-env-var TEN_SIGNALS_MCP_TOKEN", windows: "codex.cmd mcp add tensignals-local --url http://localhost:8787/mcp --bearer-token-env-var TEN_SIGNALS_MCP_TOKEN" },
    { title: "Test read-only", body: "An empty report list is correct for a new account. These calls must not start research.", command: "Use only tensignals-local. Call account_status and reports_list. Tell me the worker state and report count. Do not create anything.", expected: "mode self-hosted, worker readiness and your account's report list." },
    { title: "Create only when ready", body: "Save your OpenAI key in AI provider. Create a separate Create and read connection, reload its token, and restart the agent. Ask for report_create_preview with your domain and comparisons 20; add closePricePercent 30 for close-price matching. Approve its preview before report_create_confirm. The agent polls report_get and reads structured product links/prices with report_matches_list. Reuse the same confirmation token after an uncertain submission; no manual request ID is needed." },
    { title: "Revoke and verify", body: "Revoke the connection in Account, then ask the agent to list reports again. It should receive 401. Revocation does not cancel a report already started. Close the terminal to discard its token variable. Never expose or tunnel this loopback HTTP installation." },
  ] },
  { slug: "hosted", number: "01", title: "Use 10Signals", summary: "Create reports and watch prices in your browser.", status: "Hosted service", runsOn: "Our managed infrastructure", needs: "A 10Signals account and report allowance", boundary: "Nothing to install. Your account owns your reports; a report becomes public only when you explicitly share it.", steps: [
    { title: "Create your account", body: "Sign in or create an account. Your reports and connection settings live in Account.", href: "/account", link: "Open your account", expected: "Your account page shows your available allowance and reports." },
    { title: "Create a report", body: "Enter your own store domain. Choose a comparison target and optionally close-price matching. A comparison is one priced primary/rival product pair—not one scraped product.", href: "/", link: "Start a report", expected: "The progress screen opens, then the report shows delivered comparisons and any shortfall." },
    { title: "Read the evidence", body: "Open the original and rival product links. Prices are observed public offers. Search matches are inferred alternatives, not guaranteed identical products or savings." },
    { title: "Watch prices only when you choose", body: "Use an item's switch for that product, or the competitor-level control for a rival's products. Review cadence and credit cost before enabling. One product check uses one credit.", href: "/price-watch", link: "Open price watches" },
  ] },
  { slug: "trigger-cli", number: "02", title: "Connect the Trigger CLI", summary: "Install a client for a Trigger environment that already has the tools.", status: "Public preview", runsOn: "The Trigger environment selected by your key", needs: "Node.js 22+ and an authorized Trigger environment key", boundary: "This installs the client only. It does not install 10Signals or deploy task code. Company Trigger access is for trusted colleagues—not external customers.", steps: [
    { title: "Check Node.js", body: "Install Node.js 22 or later first if this command is unavailable. Open a new terminal after installation.", command: "node --version", href: "https://nodejs.org/en/download", link: "Get Node.js", expected: "A version of v22 or later." },
    { title: "Install the package", body: "Run from any folder. No GitHub or npm login is needed. The preview includes the native executable; a repository checkout is not required.", command: "npm install --global @10signals/cli@preview", windows: "npm.cmd install --global @10signals/cli@preview", expected: "npm reports that the package was added." },
    { title: "Verify the installed client", body: "This prints the client revision. It is different from the Trigger worker version.", command: "marketsignal-trigger version", windows: "marketsignal-trigger.cmd version", expected: "A build revision, not ‘command not found’." },
    { title: "Connect your environment", body: "Paste the environment key only at the hidden prompt. The client verifies it and saves it in your OS credential store. Never put a real key in chat, a screenshot, or a command argument.", command: "marketsignal-trigger configure", windows: "marketsignal-trigger.cmd configure", expected: "The key is verified and saved. No report is started." },
    { title: "Check the deployed tools", body: "This check makes no AI/search-provider calls. It must finish successfully. If providerConfigured is false, ask your operator to configure the research provider in Trigger before creating a report. If it stays PENDING_VERSION, your operator must promote a worker containing the Direct CLI tasks. Waiting longer is not a repair.", command: "marketsignal-trigger doctor", windows: "marketsignal-trigger.cmd doctor", expected: "COMPLETED, status ready, and four Direct CLI tasks. Research additionally requires providerConfigured true." },
    { title: "Create your first report", body: "Answer the domain, comparison count, and search-mode questions. The final confirmation starts paid research. Request IDs are automatic, and results appear in this command without a second wait command.", command: "marketsignal-trigger report", windows: "marketsignal-trigger.cmd report", expected: "A run ID, progress messages, then structured JSON with comparisons, competitors, metrics and limitations." },
    { title: "Use it from another agent", body: "Replace the domain placeholder. Argument mode submits immediately without the interactive confirmation. Add --close-price for the default ±30% same-currency displayed-price range. Never auto-retry a submission when its outcome is uncertain.", command: 'marketsignal-trigger report "<your-domain>" --comparisons 20 --close-price', windows: 'marketsignal-trigger.cmd report "<your-domain>" --comparisons 20 --close-price' },
    { title: "Read an existing result", body: "Use the run ID printed by your report command. Retrieving does not launch new research. The Windows command displays JSON directly; the macOS/Linux command saves it. Avoid Windows PowerShell 5.1 redirection for JSON files because it changes their encoding.", command: 'marketsignal-trigger result "<run-id>" > report.json', windows: 'marketsignal-trigger.cmd result "<run-id>"' },
  ] },
  { slug: "self-host", number: "03", title: "Self-host 10Signals", summary: "Install the full project and research worker on your own computer.", status: "Local quickstart preview", runsOn: "Your own computer; localhost only", needs: "Git, Docker with Compose 2.24+, your own provider key for research", boundary: "This is the full project, not the Trigger CLI. The four-command prebuilt-image preview is for owner testing; do not use these commands on the old source-build branch. No Node.js, GitHub login or certificate installation is needed. Existing HTTPS installations remain separate.", steps: [
    { title: "Choose where research runs", body: "Local execution means the application and worker run on your infrastructure. AI/search requests still need your own provider account and may cost money. The alternative is your own Trigger project; it must not use our company key." },
    { title: "Clone the quickstart preview", body: "Use a new destination folder and the public candidate branch below. Release readiness and remaining test gates are recorded in its README.", command: "git clone --branch codex/self-host-mcp https://github.com/BlyzrHQ/10signals-self-host.git 10signals", expected: "A new 10signals folder containing the project and local-only compose.yaml." },
    { title: "Open the project folder", body: "Run all following commands from this folder.", command: "cd 10signals" },
    { title: "Configure 10Signals", body: "Docker pulls the prebuilt image and creates private .env configuration automatically. No key is requested in the terminal. Existing configuration is never overwritten.", command: "docker compose run --rm setup", expected: "Private configuration saved, with the address http://localhost:8787." },
    { title: "Start 10Signals", body: "Starts the app, storage and worker together. No profile flag, local build or certificate steps. Open http://localhost:8787 and create a local account. Keep the loopback-only binding; this HTTP preview must not be exposed to the network.", command: "docker compose up -d --wait", expected: "Web, worker and gateway are healthy. Without a provider key, the app explains that research is disabled." },
    { title: "Connect your AI provider", body: "Open Account → AI provider, enter your own OpenAI API key and select Test & save. Authentication and required model access are checked without generating a report. Billing credit and inference are checked when you run a report. Keys are encrypted per account. Replace or remove a key from the same screen; no worker restart is needed." },
    { title: "Connect a local agent", body: "Local MCP has its own account-scoped connections. The general account API, scheduled watches and public-server hardening remain separate acceptance gates. Setup does not start a paid report.", href: "/docs/local-mcp", link: "Local MCP guide" },
    { title: "Acceptance checklist", body: "Start with empty storage; create an account; run a real-domain report; test private/share access and watch controls; restart and verify persistence. A home page loading successfully is not full installation acceptance." },
  ] },
  { slug: "own-trigger", number: "04", title: "Install tools in your Trigger", summary: "Deploy task code into an environment you own.", status: "Isolated setup candidate", runsOn: "Your own Trigger project", needs: "Source, Node.js, Trigger deployment access, provider credentials", boundary: "A runtime environment key can run installed tasks; it does not install them. Deployment access is separate. This installer selects your project explicitly and does not use the company configuration. An empty-project live deployment is still an acceptance gate.", steps: [
    { title: "Prepare the source", body: "Obtain the authorized source checkout and install its locked dependencies. Downloading the client is not a substitute for task code.", command: "npm ci", windows: "npm.cmd ci" },
    { title: "Preview the setup", body: "Use the codex/own-trigger-setup source candidate. Enter your own project reference, staging or production environment, and a new named operator profile. Plan mode writes nothing and does not log in or deploy.", command: "node scripts/setup-own-trigger.mjs --plan", expected: "An isolated deployment plan with no company project or credentials." },
    { title: "Install the tasks", body: "The wizard asks for a typed confirmation of your project, environment and profile before opening operator login or deploying. It uses isolated configuration, an empty environment file and skip-promotion. Inspect the actual current version in Trigger afterwards; do not assume a deployed version is live.", command: "node scripts/setup-own-trigger.mjs", expected: "A candidate task deployment in the explicitly selected project. No report is launched." },
    { title: "Connect clients afterwards", body: "Configure provider credentials in your environment, then give authorized teammates runtime access. They install the CLI and run configure, doctor and report. External customers use account API/MCP access instead." },
  ] },
  { slug: "api", number: "05", title: "Connect through the API", summary: "Let an external client use its own 10Signals account.", status: "Onboarding fixes: test candidate", runsOn: "Our hosted service", needs: "An account-scoped 10Signals API key", boundary: "This is external service access, not internal Trigger access. Customers need no Trigger, provider, VPS or company credentials. Hosted allowances still apply. The new list/status fixes await owner testing and are not yet deployed; self-hosted API support is not released.", steps: [
    { title: "Create a scoped key", body: "Open Account → API keys. Start read-only, set an expiry, and copy it once into your secret manager. Use separate keys for separate clients.", href: "/account?section=keys", link: "Open API keys" },
    { title: "Enter the key privately", body: "Run in your terminal. The prompt hides the key; do not paste it into source code or a command argument. Keep this terminal open for the next step.", windows: '$secret = Read-Host "Account API key" -AsSecureString\n$credential = [pscredential]::new("api", $secret)\n$headers = @{Authorization = "Bearer " + $credential.GetNetworkCredential().Password}', command: "printf 'Account API key: '; IFS= read -r -s SIGNALS_API_KEY; printf '\\n'" },
    { title: "Check access without spending a report", body: "This returns only your account's reports. An empty page is valid for a new account. No research starts. A revoked key returns 401.", windows: 'Invoke-RestMethod "https://10signals.xyz/api/reports?limit=10" -Headers $headers', command: 'curl --fail-with-body -H "Authorization: Bearer $SIGNALS_API_KEY" "https://10signals.xyz/api/reports?limit=10"', expected: 'ok: true, contractVersion: "1", page.items, and page.nextCursor.' },
    { title: "Prepare a paid request", body: "Switch to a create-and-read key. Replace the domain placeholder below. Hosted subscriptions use the comparison count of your plan; do not assume a smaller requested count changes that entitlement. Generate this request ID once, retaining it for an uncertain retry of the same request. The interactive Trigger CLI handles IDs for you; this low-level HTTP walkthrough makes idempotency explicit.", windows: '$requestId = [guid]::NewGuid().ToString()\n$body = @{primaryDomain="<your-domain>"; closePricePercent=30; commandId=$requestId} | ConvertTo-Json', command: 'REQUEST_ID=$(uuidgen)\nDOMAIN="<your-domain>"' },
    { title: "Submit once", body: "This starts paid work immediately. Omit closePricePercent for broad matching. Save the returned report.publicId and requestId. HTTP 202 means accepted, not finished. Do not regenerate the request ID after a timeout; inspect the existing request first.", windows: '$created = Invoke-RestMethod "https://10signals.xyz/api/reports" -Method Post -Headers $headers -ContentType "application/json" -Body $body\n$created', command: 'curl --fail-with-body -H "Authorization: Bearer $SIGNALS_API_KEY" -H "Content-Type: application/json" -d "{\\"primaryDomain\\":\\"$DOMAIN\\",\\"closePricePercent\\":30,\\"commandId\\":\\"$REQUEST_ID\\"}" https://10signals.xyz/api/reports', expected: "HTTP 202 with report.publicId and requestId; a 402 means hosted allowance is required." },
    { title: "Read status and structured results", body: "Use the returned report ID. Poll no faster than every ten seconds and respect Retry-After. A terminal result can be complete, partial or failed. The result/comparisons endpoint with the same requestId provides further comparison pages. A missing, expired or unauthorized report returns 404 without revealing whether it belongs to someone else.", windows: '$reportId = $created.report.publicId\nInvoke-RestMethod "https://10signals.xyz/api/reports/$reportId" -Headers $headers\nInvoke-RestMethod "https://10signals.xyz/api/reports/$reportId/result?requestId=$requestId" -Headers $headers | ConvertTo-Json -Depth 100', command: 'REPORT_ID="<returned-report-id>"\ncurl --fail-with-body -H "Authorization: Bearer $SIGNALS_API_KEY" "https://10signals.xyz/api/reports/$REPORT_ID"\ncurl --fail-with-body -H "Authorization: Bearer $SIGNALS_API_KEY" "https://10signals.xyz/api/reports/$REPORT_ID/result?requestId=$REQUEST_ID"', expected: "Owned report state, then structured comparisons, competitors, source links and limitations." },
    { title: "Revoke and verify", body: "Revoke the test key in Account. Repeat the list check and confirm 401. Close the terminal to discard in-memory secret variables. Read-only denial, account isolation and revocation have automated tests; a live paid new-customer lifecycle remains an acceptance gate." },
    { title: "Which CLI is this?", body: "The customer binary is marketsignal and uses an account key. The public @10signals/cli preview installs marketsignal-trigger for internal/own-Trigger use, not the customer binary. The HTTP commands above need no extra client package." },
  ] },
  { slug: "mcp", number: "06", title: "Connect an AI agent with MCP", summary: "Give an agent scoped report and price-watch tools.", status: "Discovery checked / client acceptance pending", runsOn: "Our hosted service", needs: "A compatible OAuth MCP client and your account consent", boundary: "An account API key is not an MCP OAuth token. No Trigger key is needed. Your agent must ask before paid report creation or recurring price checks. Live discovery was checked; external-client login is still an acceptance gate. Independent self-hosted OAuth is not released.", steps: [
    { title: "Add the remote MCP server", body: "In your client's remote-server settings, use the hosted endpoint below. This connects to our service; it does not install a local server.", command: "https://10signals.xyz/mcp" },
    { title: "Authorize your account", body: "Follow the client's OAuth sign-in and consent flow. Start with reports:read. Review the actual client host. The server uses OAuth discovery and CIMD; old clients that only support dynamic registration may not connect. Do not work around an OAuth error by sharing a company key." },
    { title: "Start read-only", body: "Ask your agent to call account_status and reports_list, then report_get and report_matches_list for an owned report. Empty history is valid for a new account. These checks must not create reports or watches.", command: "List my reports and show one report's comparison evidence. Do not create a report or enable any price watches." },
    { title: "Control paid work explicitly", body: "report_create_preview shows the current plan's comparison count and allowance impact; only report_create_confirm starts work. price_watch_preview shows product/rival scope, cadence and credits; only price_watch_confirm activates. Keep the same token for an uncertain retry. Disable the test watch with price_watch_disable. Tokens expire after five minutes; obtain a new preview if impact changes or the token expires." },
    { title: "Run the no-cost diagnostic", body: "From the source candidate, this Node.js command checks public metadata and the unauthenticated 401 challenge. It does not log in, access your data or call paid tools. A successful check is not proof of client compatibility.", command: "node scripts/check-mcp-connection.mjs", windows: "node scripts/check-mcp-connection.mjs", expected: "discovery: available; authentication: required; clientLoginTested: false; toolsTested: false." },
    { title: "Revoke the test connection", body: "Remove the OAuth connection from Account → Connected apps and verify access fails. API keys are separate and must be revoked separately.", href: "/account?section=apps", link: "Open connected apps" },
  ] },
].sort((left, right) => left.number.localeCompare(right.number));
