import React from 'react';
import { NavBar } from '../../components/navigation/NavBar.jsx';
import { Button } from '../../components/actions/Button.jsx';
import { Tag } from '../../components/labels/Tag.jsx';
import { Card } from '../../components/surfaces/Card.jsx';
import { EvidencePill } from '../../components/labels/EvidencePill.jsx';
import { Input } from '../../components/forms/Input.jsx';
import { Segmented } from '../../components/forms/Segmented.jsx';
import { Select } from '../../components/forms/Select.jsx';
export function Account({ onHome, onReport, onSignOut }) {
  const [sec, setSec] = React.useState('reports');
  const [keys, setKeys] = React.useState([{ id:'k1', name:'Nightly research agent', last4:'7pRm', scope:'Create and read reports', meta:'Expires 6 Dec 2026 · Last used today', active:true },{ id:'k2', name:'Dashboard read-only', last4:'Q2xa', scope:'Read reports only', meta:'Revoked', active:false }]);
  const [revealed, setRevealed] = React.useState(false);
  const nav = [['reports','My reports'],['plan','Plan & usage'],['profile','Profile'],['keys','API keys'],['apps','Connected apps']];
  const row = { display:'grid', gap:14, alignItems:'center', padding:'10px 12px', background:'var(--surface-raised)', border:'1px solid var(--border)', borderRadius:'var(--radius-lg)', fontSize:13 };
  return <div style={{maxWidth:1120,margin:'0 auto',padding:'0 28px 80px'}}>
    <NavBar logoSrc="../../assets/logo-dot.png" crumbs={['Account']} onBrandClick={onHome}><Button variant="secondary" size="sm" onClick={onReport}>Open latest report</Button><Button variant="ghost" size="sm" onClick={onSignOut}>Sign out</Button></NavBar>
    <div style={{display:'flex',alignItems:'center',gap:10,margin:'14px 0 22px'}}><span style={{width:44,height:44,borderRadius:'50%',background:'var(--primary-tint)',color:'var(--primary-deep)',fontWeight:600,display:'grid',placeItems:'center'}}>MB</span><div><h1 style={{fontSize:22,fontWeight:600,margin:0}}>Moe Bannaa</h1><p dir="ltr" style={{margin:0,fontSize:13,color:'var(--text-muted)',textAlign:'start'}}>moe@bannaa.co</p></div><Tag variant="planned" style={{marginInlineStart:6}}>Planned</Tag><span style={{fontSize:12,color:'var(--text-faint)'}}>Planned capability — shown as a proposal, not live</span></div>
    <div style={{display:'grid',gridTemplateColumns:'200px minmax(0,1fr)',gap:28,alignItems:'start'}}>
      <nav style={{display:'grid',gap:2}}>{nav.map(([k,l]) => <button key={k} aria-current={sec===k} onClick={()=>setSec(k)} style={{textAlign:'start',border:0,background:sec===k?'var(--primary-tint)':'transparent',color:sec===k?'var(--primary-deep)':'var(--text-body)',padding:'8px 12px',borderRadius:999,cursor:'pointer',fontSize:14,fontWeight:sec===k?600:400,fontFamily:'inherit'}}>{l}</button>)}</nav>
      <div style={{display:'grid',gap:14}}>
        {sec==='reports' && <Card title="My reports"><div style={{display:'grid',gap:4}}>
          {[['lumenandoak.com','observed','Complete','4 competitors · 27 comparisons','14 Aug 2026'],['lumenandoak.com','limited','Limited','3 competitors · 14 comparisons · ads not checked','2 Jul 2026'],['northlightcandles.com','observed','Complete','5 competitors · 31 comparisons','19 Jun 2026'],['example-store.com','unavailable','Failed','Parked domain — no storefront found','11 Jun 2026']].map(([d,s,l,m,dt],i) => <button key={i} onClick={onReport} style={{...row,gridTemplateColumns:'minmax(0,1.4fr) auto minmax(0,1fr) auto',textAlign:'start',cursor:'pointer',fontFamily:'inherit',color:'var(--text)'}}><span dir="ltr" style={{fontSize:14,textAlign:'start'}}>{d}</span><EvidencePill state={s} uppercase>{l}</EvidencePill><span style={{fontSize:12,color:'var(--text-muted)'}}>{m}</span><span style={{fontSize:12,color:'var(--text-faint)',fontVariantNumeric:'tabular-nums'}}>{dt}</span></button>)}
        </div><p style={{fontSize:12,color:'var(--text-faint)',margin:'12px 0 0'}}>Reports are saved to unlisted links; attaching them to an account is planned and does not restrict who can open the link.</p></Card>}
        {sec==='plan' && <Card title="Plan & usage">
          <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12,marginBottom:14}}>
            <Card variant="raised" kicker="Current plan" padding="12px 14px"><p style={{margin:0,fontSize:20,fontWeight:600}}>Solo</p><p style={{margin:'2px 0 0',fontSize:12,color:'var(--text-muted)'}}>$29 / month · nothing charged in preview</p></Card>
            <Card variant="raised" kicker="Reports this period" padding="12px 14px"><p style={{margin:0,fontSize:20,fontWeight:600,fontVariantNumeric:'tabular-nums'}}>4 <span style={{fontSize:13,color:'var(--text-muted)'}}>/ 10</span></p><div style={{height:6,background:'var(--surface-sunken)',borderRadius:3,marginTop:8,overflow:'hidden'}}><div style={{width:'40%',height:'100%',background:'var(--primary)'}}/></div></Card>
            <Card variant="raised" kicker="Products per report" padding="12px 14px"><p style={{margin:0,fontSize:20,fontWeight:600,fontVariantNumeric:'tabular-nums'}}>50</p><p style={{margin:'2px 0 0',fontSize:12,color:'var(--text-muted)'}}>Period resets 1 Oct 2026</p></Card>
          </div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}>{[['Starter','$8','5 reports · 20 products/report'],['Solo','$29','10 reports · 50 products/report'],['Growth','$79','40 reports · 500 products/report'],['Agency','$199','120 reports · 1,000 products/report']].map(([n,p,b]) => <Card key={n} variant="raised" padding="12px 14px" style={{borderColor:n==='Solo'?'var(--primary)':'var(--border)'}}><p style={{margin:0,fontSize:10,letterSpacing:'.08em',textTransform:'uppercase',color:'var(--primary)'}}>{n}</p><p dir="ltr" style={{margin:0,fontSize:18,fontWeight:600,fontVariantNumeric:'tabular-nums',textAlign:'start'}}>{p}<span style={{fontSize:12,color:'var(--text-muted)',fontWeight:400}}> / month</span></p><p style={{margin:0,fontSize:12,color:'var(--text-muted)'}}>{b}</p><Button variant="secondary" size="sm" disabled={n==='Solo'} style={{marginTop:8}}>{n==='Solo'?'Current plan':'Choose'}</Button></Card>)}</div>
          <p style={{fontSize:12,color:'var(--text-faint)',margin:'12px 0 0'}}>Prices are launch targets. Checkout and the billing portal are not connected in this preview.</p>
        </Card>}
        {sec==='profile' && <Card title="Profile"><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12,maxWidth:640}}><Input label="Name" defaultValue="Moe Bannaa"/><Input label="Email" ltr defaultValue="moe@bannaa.co"/><label style={{display:'grid',gap:5,fontSize:12,color:'var(--text-muted)'}}>Language<Segmented value="en" onChange={()=>{}} options={[{value:'en',label:'English'},{value:'ar',label:'العربية'}]}/></label><label style={{display:'grid',gap:5,fontSize:12,color:'var(--text-muted)'}}>Password<span><Button variant="secondary" size="sm">Change password</Button></span></label></div><div style={{marginTop:14}}><Button>Save changes</Button></div><div style={{marginTop:24,paddingTop:14,borderTop:'1px solid var(--border)'}}><p style={{margin:'0 0 4px',fontSize:10,letterSpacing:'.08em',textTransform:'uppercase',color:'var(--text-muted)'}}>Danger zone</p><p style={{margin:'0 0 8px',fontSize:13,color:'var(--text-body)'}}>Deleting the account removes sign-in and API keys. Saved report links stay reachable until retention controls ship (planned).</p><Button variant="secondary" size="sm">Delete account</Button></div></Card>}
        {sec==='keys' && <Card title="API keys">
          <p style={{margin:'0 0 14px',fontSize:13,color:'var(--text-muted)',maxWidth:640}}>Create an account-scoped key when a browser login is not practical. The full key is shown once.</p>
          <form onSubmit={e=>{e.preventDefault();setRevealed(true);setKeys(k=>[{id:'k'+Date.now(),name:'New key',last4:'NwT',scope:'Create and read reports',meta:'Expires 7 Dec 2026 · Never used',active:true},...k]);}} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10,alignItems:'end',marginBottom:12}}><Input label="Key name" placeholder="Nightly research agent"/><Select label="Access" options={[{value:'full',label:'Create and read reports'},{value:'read',label:'Read reports only'}]}/><Select label="Expires" options={[{value:'30',label:'30 days'},{value:'90',label:'90 days'},{value:'365',label:'1 year'}]}/><Button type="submit" style={{justifySelf:'start'}}>Create key</Button></form>
          {revealed && <div role="status" style={{background:'var(--primary-tint)',borderRadius:'var(--radius-lg)',padding:'12px 14px',marginBottom:12,fontSize:13}}><p style={{margin:'0 0 6px',fontWeight:600}}>Copy this key now. It will not be shown again.</p><div style={{display:'flex',gap:8,alignItems:'center'}}><code dir="ltr" style={{flex:1,fontFamily:'var(--font-mono)',fontSize:12,background:'var(--surface-raised)',border:'1px solid var(--border-strong)',borderRadius:10,padding:'8px 10px'}}>tsg_live_4Kq9…c2Vd7pRm1xLz8NwT</code><Button variant="secondary" size="sm">Copy key</Button></div></div>}
          <div style={{display:'grid',gap:4}}>{keys.map(k => <div key={k.id} style={{...row,gridTemplateColumns:'minmax(0,1fr) auto auto'}}><span><span style={{display:'block'}}>{k.name}</span><span dir="ltr" style={{fontSize:12,color:'var(--text-muted)',display:'block',textAlign:'start'}}>•••• {k.last4} · {k.scope}</span></span><span style={{fontSize:12,color:'var(--text-faint)'}}>{k.meta}</span>{k.active ? <Button variant="secondary" size="sm" onClick={()=>setKeys(ks=>ks.map(x=>x.id===k.id?{...x,active:false,meta:'Revoked'}:x))}>Revoke</Button> : <span/>}</div>)}</div>
        </Card>}
        {sec==='apps' && <Card title="Connected apps"><p style={{margin:'0 0 14px',fontSize:13,color:'var(--text-muted)',maxWidth:640}}>The 10 Signals CLI, Claude, Codex and other clients appear here after you approve access. Client names are self-asserted; check the host before connecting.</p><div style={{display:'grid',gap:4}}>{[['10 Signals CLI','cli.10signals.app · Verified client','observed','Active'],['Claude','claude.ai · Unverified identity','limited','Reauthorization required']].map(([n,h,s,l]) => <div key={n} style={{...row,gridTemplateColumns:'minmax(0,1fr) auto auto'}}><span><span style={{display:'block'}}>{n}</span><span dir="ltr" style={{fontSize:12,color:'var(--text-muted)',display:'block',textAlign:'start'}}>{h}</span></span><EvidencePill state={s}>{l}</EvidencePill><Button variant="secondary" size="sm">Revoke</Button></div>)}</div></Card>}
      </div>
    </div>
  </div>;
}
