import { randomBytes } from "node:crypto";
import { open, lstat, readFile, rename, unlink, link } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline/promises";
import { Writable } from "node:stream";

const marker = "# 10Signals local quickstart configuration v1";
export function localEnvironment({ providerKey = "", port = 8787, secret = randomBytes(32).toString("hex") } = {}) {
  if (!Number.isInteger(port) || port < 1024 || port > 65535) throw Error("Choose a port from 1024 to 65535.");
  if (!/^[A-Za-z0-9_-]*$/.test(providerKey)) throw Error("The provider key contains unsupported characters.");
  if (!/^[a-f0-9]{64}$/.test(secret)) throw Error("Invalid account secret.");
  return `${marker}\n# Private: never commit or share this file.\nTEN_SIGNALS_PORT=${port}\nTEN_SIGNALS_AUTH_SECRET=${secret}\nTEN_SIGNALS_PROVIDER_KEY=${providerKey}\n`;
}

export async function saveLocalEnvironment(directory, options, setKey = false, persist = (file, content) => file.writeFile(content, "utf8")) {
  const root = resolve(directory), target = resolve(root, ".env");
  const owner = await lstat(root);
  if (!owner.isDirectory() || owner.isSymbolicLink()) throw Error("Setup requires a regular installation directory.");
  let previous;
  if (setKey) {
    const info = await lstat(target);
    if (!info.isFile() || info.isSymbolicLink()) throw Error("Refusing to change a non-regular .env file.");
    previous = await readFile(target, "utf8");
    const match = /^# 10Signals local quickstart configuration v1\n# Private: never commit or share this file\.\nTEN_SIGNALS_PORT=(\d+)\nTEN_SIGNALS_AUTH_SECRET=([a-f0-9]{64})\nTEN_SIGNALS_PROVIDER_KEY=([A-Za-z0-9_-]*)\n$/.exec(previous.replaceAll("\r\n", "\n"));
    if (!match) throw Error("This .env was not generated by this installer. No changes made.");
    options = { ...options, port: Number(match[1]), secret: match[2] };
  }
  const content = localEnvironment(options);
  const temporary = resolve(root, `.env.setup-${randomBytes(12).toString("hex")}`);
  try {
    const file = await open(temporary, "wx", 0o600);
    try {
      // Docker runs setup as root; retain host directory ownership on Linux.
      if (process.getuid?.() === 0) await file.chown(owner.uid, owner.gid);
      await persist(file, content);
      await file.sync();
    } finally { await file.close(); }
    if (setKey) {
      const info = await lstat(target);
      if (!info.isFile() || info.isSymbolicLink() || await readFile(target, "utf8") !== previous) throw Error("Configuration changed during setup. No changes made.");
      await rename(temporary, target);
    } else {
      // Atomic publication without replacing a concurrently created .env.
      await link(temporary, target);
    }
  } finally { await unlink(temporary).catch(error => { if (error.code !== "ENOENT") throw error; }); }
  return { port: options.port ?? 8787, researchEnabled: Boolean(options.providerKey) };
}

async function hiddenKey() {
  if (!process.stdin.isTTY) throw Error("Use an interactive terminal, --key-stdin, or --without-provider for installation-only testing.");
  const output = new Writable({ write(_chunk, _encoding, callback) { callback(); } });
  const rl = createInterface({ input: process.stdin, output, terminal: true });
  process.stdout.write("Your OpenAI provider key (hidden; Enter skips research): ");
  try { return (await rl.question("")).trim(); } finally { rl.close(); process.stdout.write("\n"); }
}

async function main() {
  const args = process.argv.slice(2);
  if (args.includes("--help")) {
    console.log("docker compose run --rm setup [--port 8787] [--without-provider | --key-stdin] [--set-key]\nCreates private .env. --set-key changes only the provider key in an existing installer-generated .env. Existing accounts and reports are preserved."); return;
  }
  if (args.some((a, i) => !["--port", "--without-provider", "--key-stdin", "--set-key"].includes(a) && args[i - 1] !== "--port") || (args.includes("--without-provider") && args.includes("--key-stdin")) || (args.includes("--set-key") && args.includes("--port"))) throw Error("Invalid arguments. Use --help.");
  const port = args.includes("--port") ? Number(args[args.indexOf("--port") + 1]) : 8787;
  let providerKey = "";
  if (args.includes("--key-stdin")) {
    if (process.stdin.isTTY) throw Error("--key-stdin requires piped input, not a terminal.");
    for await (const chunk of process.stdin) { providerKey += chunk; if (providerKey.length > 4096) throw Error("Provider input is too long."); }
    providerKey = providerKey.trim();
  } else if (!args.includes("--without-provider")) providerKey = await hiddenKey();
  const result = await saveLocalEnvironment(process.cwd(), { providerKey, port }, args.includes("--set-key"));
  console.log("Private configuration saved. No credentials printed.");
  console.log("Next: docker compose up -d --wait");
  console.log(`Open http://localhost:${result.port} and create a local account.`);
  console.log(result.researchEnabled ? "The local research worker starts automatically. Provider usage is billed by your provider." : "Research is disabled until you run docker compose run --rm setup --set-key and then docker compose up -d --wait.");
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().catch(error => {
  console.error(error.code === "EEXIST" ? ".env already exists. Use setup --set-key to change the provider key; existing configuration was not overwritten." : error.code === "ENOENT" ? "Installation folder or .env is missing. Run setup first." : error.message);
  process.exitCode = 1;
});
